apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxplus-deployment
  namespace: nginxplus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxplus
  template:
    metadata:
      labels:
        app: nginxplus
    spec:
      containers:
      - name: nginxplus
        # Replace the image below with the correct Docker Hub image for NGINX Plus
        image: shawnnjj/thalendriousque:3.19
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxplus-service
  namespace: nginxplus
spec:
  type: NodePort
  selector:
    app: nginxplus
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    # Optionally, you can specify a fixed node port (30080 in this example).
    # If you omit nodePort, Kubernetes will automatically assign one from the allowed range.
    nodePort: 30080
